---
- name: Create the automation metrics settings configuration
  ansible.builtin.template:
    src: settings.yaml.j2
    dest: '{{ automationmetrics_config_path }}/settings.yaml'
    mode: '0640'
  notify:
    - Restart automation metrics web
    - Restart automation metrics tasks
    - Restart automation metrics scheduler

- name: Create the automation metrics web supervisord configuration
  ansible.builtin.template:
    src: supervisord_web.conf.j2
    dest: '{{ automationmetrics_config_path }}/supervisord_web.conf'
    mode: '0640'
  notify: Restart automation metrics web
...
