---
- name: Set ansiblemcp hostname, port(s) and protocol
  ansible.builtin.set_fact:
    _mcp_hostname: '{{ routable_hostname | default(ansible_host) }}'
    _mcp_port: '{{ (mcp_nginx_disable_https | bool) | ternary(mcp_nginx_http_port, mcp_nginx_https_port) }}'
    _mcp_ports: ["{{ mcp_nginx_http_port | int }}"]
    _mcp_protocol: '{{ (mcp_nginx_disable_https | bool) | ternary("http", "https") }}'

- name: Add https port to ansiblemcp port list
  ansible.builtin.set_fact:
    _mcp_ports: "{{ _mcp_ports | union([mcp_nginx_https_port]) | map('int') | list }}"
  when: not mcp_nginx_disable_https | bool

- name: Set ansiblemcp URL
  ansible.builtin.set_fact:
    _mcp_instance_url: >-
      {{ _mcp_protocol }}://{{ __mcp_instance_host }}
  vars:
    __mcp_hostname: '{{ _mcp_hostname | ansible.containerized_installer.ipv6_wrap }}'
    __mcp_instance_host: >-
      {{ (_mcp_port | int in [80, 443]) | ternary(__mcp_hostname, __mcp_hostname + ":" + (_mcp_port | string)) }}

- name: Set ansiblemcp IPs
  ansible.builtin.set_fact:
    _mcp_ips: '{{ _mcp_ips | default([]) | union(["IP:" + item]) }}'
  loop: '{{ ansible_all_ipv4_addresses + ansible_all_ipv6_addresses }}'

- name: Set ansiblemcp secrets
  ansible.builtin.set_fact:
    _mcp_secrets:
      - 'mcp_telemetry_hmac_key,type=env,target=TELEMETRY_HMAC_KEY'
      - 'mcp_installer_id,type=env,target=INSTALLER_ID'

- name: Set ansiblemcp volumes
  ansible.builtin.set_fact:
    _common_volumes:
      - '{{ _ca_tls_dir }}/extracted:/etc/pki/ca-trust/extracted:z'
    _nginx_volumes:
      - '{{ mcp_nginx_conf_dir }}/nginx.conf:/etc/nginx/nginx.conf:ro,z'
      - 'mcp_nginx:/var/lib/nginx:U'

- name: Set ansiblemcp volumes
  ansible.builtin.set_fact:
    _mcp_volumes: '{{ _common_volumes + _nginx_volumes }}'

- name: Add tls to ansiblemcp volumes
  ansible.builtin.set_fact:
    _mcp_volumes: '{{ _mcp_volumes + _tls_volumes }}'
  vars:
    _tls_volumes:
      - '{{ mcp_conf_dir }}/ansiblemcp.cert:/etc/ansible-automation-platform/ansiblemcp/ansiblemcp.crt:ro,z'
      - '{{ mcp_conf_dir }}/ansiblemcp.key:/etc/ansible-automation-platform/ansiblemcp/ansiblemcp.key:ro,z'
  when: not mcp_nginx_disable_https | bool
...
