---
- name: Create the automation metrics web container
  containers.podman.podman_container:
    name: automation-metrics-web
    image: '{{ _automationmetrics_image }}'
    command: 'supervisord -n -c /etc/supervisord_web.conf'
    generate_systemd:
      container_prefix: ''
      path: '{{ ansible_user_dir }}/.config/systemd/user'
      separator: ''
      requires: '{{ __systemd_requires }}'
      restart_policy: always
    log_driver: '{{ container_log_driver }}'
    user: '{{ ansible_user_uid }}'
    userns: keep-id
    network: host
    mount:
      - 'type=tmpfs,destination=/run/nginx,U=true'
      - 'type=tmpfs,destination=/run/supervisor,U=true'
    secrets: '{{ _common_secrets }}'
    volume: '{{ _web_volumes }}'
    env: '{{ _automationmetrics_env }}'
    label:
      '{{ _autoupdate_label }}'
    state: created
    recreate: '{{ __containers_recreate | default(false) }}'
  notify: Restart automation metrics web

- name: Create the automation metrics tasks container
  containers.podman.podman_container:
    name: automation-metrics-tasks
    image: '{{ _automationmetrics_image }}'
    command: >-
      metrics-service dispatcherd
      --workers {{ automationmetrics_dispatcherd_workers }}
      --timeout {{ automationmetrics_dispatcherd_timeout }}
      --max-tasks {{ automationmetrics_dispatcherd_max_tasks }}
    generate_systemd:
      container_prefix: ''
      path: '{{ ansible_user_dir }}/.config/systemd/user'
      separator: ''
      requires: '{{ __systemd_requires }}'
      restart_policy: always
    log_driver: '{{ container_log_driver }}'
    user: '{{ ansible_user_uid }}'
    userns: keep-id
    network: host
    secrets: '{{ _common_secrets }}'
    volume: '{{ _task_volumes }}'
    env: '{{ _automationmetrics_env }}'
    label:
      '{{ _autoupdate_label }}'
    state: created
    recreate: '{{ __containers_recreate | default(false) }}'
  notify: Restart automation metrics tasks

- name: Create the automation metrics scheduler container
  containers.podman.podman_container:
    name: automation-metrics-scheduler
    image: '{{ _automationmetrics_image }}'
    command: 'metrics-service scheduler --check-interval {{ automationmetrics_scheduler_check_interval }}'
    generate_systemd:
      container_prefix: ''
      path: '{{ ansible_user_dir }}/.config/systemd/user'
      separator: ''
      requires: '{{ __systemd_requires }}'
      restart_policy: always
    log_driver: '{{ container_log_driver }}'
    user: '{{ ansible_user_uid }}'
    userns: keep-id
    network: host
    secrets: '{{ _common_secrets }}'
    volume: '{{ _scheduler_volumes }}'
    env: '{{ _automationmetrics_env }}'
    label:
      '{{ _autoupdate_label }}'
    state: created
    recreate: '{{ __containers_recreate | default(false) }}'
  notify: Restart automation metrics scheduler
...
