---
- name: Create systemd user directory
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.config/systemd/user"
    state: directory
    mode: '0755'

- name: Create lightspeed token cleanup timers
  ansible.builtin.copy:
    src: '{{ item.src }}'
    dest: '{{ ansible_user_dir }}/.config/systemd/user/{{ item.dest }}'
    mode: '0644'
  loop:
    - src: lightspeed-revoke-expired-tokens.timer
      dest: ansible-lightspeed-revoke-expired-tokens.timer
    - src: lightspeed-cleartokens.timer
      dest: ansible-lightspeed-cleartokens.timer
  loop_control:
    label: '{{ item.dest }}'

- name: Enable and start lightspeed token cleanup timers
  ansible.builtin.systemd_service:
    name: '{{ item }}'
    scope: user
    enabled: true
    state: started
    daemon_reload: true
  loop:
    - ansible-lightspeed-revoke-expired-tokens.timer
    - ansible-lightspeed-cleartokens.timer
...
