---
collections:
  - name: ansible.posix
    version: 1.5.4
  - name: community.crypto
    version: 2.26.7
  - name: community.postgresql
    version: 3.14.3
  - name: containers.podman
    version: 1.17.0
  - name: infra.ah_configuration
    version: 2.0.6
  - name: infra.controller_configuration
    version: 2.9.0
  - name: vendor/ansible-controller-4.7.12.tar.gz
  - name: vendor/ansible-platform-2.6.20260504.tar.gz
...
