---
stages:
  - build
  - lint
  - test
  - functional_test
  - deploy

# Needed to properly structure pipeline and see all the results for MR
# see https://medium.com/devops-with-valentine/fix-gitlab-ci-duplicate-pipelines-in-merge-requests-when-using-rules-9a1486994f3a
workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'

default:
  tags:
    - itup-alm-x86

image: quay.io/centos/centos:stream9-minimal

before_script:
  - microdnf install -y --nodocs --setopt=install_weak_deps=0 ansible-core diffutils python3-pip

black:
  stage: lint
  script:
    - pip install black
    - black --check --diff plugins

changelog:
  stage: lint
  script:
    - pip install antsibull-changelog
    - antsibull-changelog lint

collection:
  stage: build
  script:
    - ansible-galaxy collection build

flake8:
  stage: lint
  script:
    - pip install flake8
    - flake8 plugins

lint:
  stage: lint
  script:
    - pip install ansible-lint
    - ansible-galaxy collection install -r requirements.yml
    - ansible-galaxy collection install .
    - ansible-lint

nbsp:
  stage: lint
  script:
    - grep --exclude-dir=.git --exclude-dir=vendor -P "\xa0" -r . || true
    - if [[ -n $(grep --exclude-dir=.git --exclude-dir=vendor -P "\xa0" -r .) ]]; then echo 'NBSP characters found.'; exit 1; fi

ports:
  stage: lint
  script:
    - egrep -r -e '_https?_port:' roles | sort -n -k2 > ports.txt
    - egrep -r -e '_https?_port:' roles | sort -n -k2 -u > unique_ports.txt
    - if [ -n "$(diff -uN unique_ports.txt ports.txt)" ]; then echo 'HTTP(S) port conflict detected'; diff -uN unique_ports.txt ports.txt; exit 1; fi

include: '.gitlab-ci-functional-test.yml'
