---
# Functional tests.
# Those can be only run inside the project and not fork
# because we set several secrets vars to connect to private repos and decrypt secrets
# TODO: consider movig to the new file
variables:
  ansible_host_key_checking: 'false'
  ansible_force_color: 'true'

test-online-1hybr-1gw-1db-rhel96:
  tags:
    - pde-aws-runner
  image: &FUNCTIONAL_IMAGE
    name: quay.io/aap-ci/ansible-jenkins-agent:latest
    entrypoint: [""]
  stage: functional_test
  before_script: &INJECT_KEY
    - |
      eval $(ssh-agent -s)
      echo "${AAPQA_SSH_PRIVATE_KEY}" | tr -d '\r' | ssh-add -
      mkdir -p ~/.ssh
      chmod 700 ~/.ssh
      echo ${AAPQA_SSH_PRIVATE_KEY} > ~/.ssh/id_rsa.pub && chmod 0600 ~/.ssh/id_rsa.pub
  script:
    - |
      pushd tests/functional_test
      cat >parameters.yml <<EOL
      ---
      provision_prefix: 'gitlabci-${CI_JOB_ID}-minimal_online_rhel96'
      provision_cloud: 'input/provisioner/cloud/aws.yml'
      provision_topology: 'input/aap_scenarios/1inst_1hybr_1gw_1db.yml'
      provision_platform: 'input/platform/rhel96.yml'
      provision_extra_args: '-e @input/provisioner/additional_nodes/1automationmetrics.yml'
      run_idempotence_installer: false
      installer_vars:
        gateway_admin_password: adminpassword
        gateway_pg_host: database-0
        gateway_pg_password: addminpassword
        controller_admin_password: adminpassword
        postgresql_admin_password: adminpassword
        controller_pg_host: database-0
        controller_pg_password: adminpassword
        registry_username: ${AAPQUAY_REGISTRY_USERNAME}
        registry_password: ${AAPQUAY_REGISTRY_PASSWORD}
        redis_mode: standalone
        postgresql_image: 'rhel9-postgresql-15:latest'
        redis_image: 'rhel9-redis-6:latest'
        pcp_image: 'rhel9-pcp:latest'
        registry_url: quay.io
        registry_ns_aap: aap/ansible-automation-platform-27-next
        registry_ns_aap_tp: aap/ansible-automation-platform-27-next
        registry_ns_rhel: aap
        automationmetrics_admin_password: adminpassword
        automationmetrics_pg_host: database-0
        automationmetrics_pg_password: adminpassword
        automationmetrics_controller_read_pg_host: database-0
        automationmetrics_controller_read_pg_password: adminpassword
      ...
      EOL
      ansible-playbook run_scenario.yml -e @parameters.yml
  rules: &FUNCTIONAL_RULES
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" && $CI_PROJECT_NAMESPACE == "ansible"'
      changes: &ON_INSTALLER_CHANGES
        - playbooks/**/*
        - roles/**/*
        - tests/functional_test/**/*
        - requirements.yml
        - .gitlab-ci.yml
        - .gitlab-ci-functional-test.yml

test-offline-1hybr-1gw-1db-rhel96:
  tags:
    - pde-aws-runner
  timeout: 2h
  variables:
    RUNNER_SCRIPT_TIMEOUT: 110m
  image: *FUNCTIONAL_IMAGE
  stage: functional_test
  before_script: *INJECT_KEY
  script:
    - |
      pushd tests/functional_test
      cat >parameters.yml <<EOL
      ---
      provision_prefix: 'gitlabci-${CI_JOB_ID}-minimal_offline_rhel96'
      provision_cloud: 'input/provisioner/cloud/aws.yml'
      provision_topology: 'input/aap_scenarios/1inst_1hybr_1gw_1db.yml'
      provision_platform: 'input/platform/rhel96.yml'
      provision_extra_args: '-e @input/provisioner/additional_nodes/1automationmetrics.yml'
      run_idempotence_installer: false
      installer_vars:
        bundle_install: true
        container_compress: pigz
        gateway_admin_password: adminpassword
        gateway_pg_host: database-0
        gateway_pg_password: addminpassword
        controller_admin_password: adminpassword
        postgresql_admin_password: adminpassword
        controller_pg_host: database-0
        controller_pg_password: adminpassword
        registry_username: ${AAPQUAY_REGISTRY_USERNAME}
        registry_password: ${AAPQUAY_REGISTRY_PASSWORD}
        redis_mode: standalone
        postgresql_image: 'rhel9-postgresql-15:latest'
        redis_image: 'rhel9-redis-6:latest'
        pcp_image: 'rhel9-pcp:latest'
        registry_url: quay.io
        registry_ns_aap: aap/ansible-automation-platform-27-next
        registry_ns_aap_tp: aap/ansible-automation-platform-27-next
        registry_ns_rhel: aap
        automationmetrics_admin_password: adminpassword
        automationmetrics_pg_host: database-0
        automationmetrics_pg_password: adminpassword
        automationmetrics_controller_read_pg_host: database-0
        automationmetrics_controller_read_pg_password: adminpassword
      ...
      EOL
      ansible-playbook run_scenario.yml -e @parameters.yml
  rules: *FUNCTIONAL_RULES

test-online-all-in-one-rhel96:
  tags:
    - pde-aws-runner
  image: *FUNCTIONAL_IMAGE
  stage: functional_test
  before_script: *INJECT_KEY
  script:
    - |
      pushd tests/functional_test
      cat >parameters.yml <<EOL
      ---
      provision_prefix: 'gitlabci-${CI_JOB_ID}-eda_hub_rhel96'
      provision_cloud: 'input/provisioner/cloud/aws.yml'
      provision_topology: 'input/aap_scenarios/1inst_1aio.yml'
      provision_platform: 'input/platform/rhel96.yml'
      installer_vars:
        bundle_install: false
        gateway_admin_password: adminpassword
        gateway_pg_host: aio-0
        gateway_pg_password: addminpassword
        controller_admin_password: adminpassword
        postgresql_admin_password: adminpassword
        controller_pg_host: aio-0
        controller_pg_password: adminpassword
        controller_percent_memory_capacity: 0.5
        registry_username: ${AAPQUAY_REGISTRY_USERNAME}
        registry_password: ${AAPQUAY_REGISTRY_PASSWORD}
        eda_admin_password: adminpassword
        eda_pg_host: aio-0
        eda_pg_password: adminpassword
        hub_admin_password: adminpassword
        hub_pg_host: aio-0
        hub_pg_password: adminpassword
        redis_mode: standalone
        postgresql_image: 'rhel9-postgresql-15:latest'
        redis_image: 'rhel9-redis-6:latest'
        pcp_image: 'rhel9-pcp:latest'
        registry_url: quay.io
        registry_ns_aap: aap/ansible-automation-platform-27-next
        registry_ns_aap_tp: aap/ansible-automation-platform-27-next
        registry_ns_rhel: aap
        automationmetrics_admin_password: adminpassword
        automationmetrics_pg_host: aio-0
        automationmetrics_pg_password: adminpassword
        automationmetrics_controller_read_pg_host: aio-0
        automationmetrics_controller_read_pg_password: adminpassword
      ...
      EOL
      ansible-playbook run_scenario.yml -e @parameters.yml
  rules: *FUNCTIONAL_RULES
...
