---
- name: Backup the PostgreSQL database
  when: not eda_postgresql_skip_data | bool or groups.get('database', []) | length == 1
  block:
    - name: Create postgresql CLI aliases
      ansible.builtin.include_role:
        name: postgresql
        tasks_from: cli.yml
      vars:
        _postgresql_socket: '{{ eda_pg_socket | default("") }}'
        _postgresql_cert_auth: '{{ eda_pg_cert_auth }}'
        _postgresql_src_dir: '{{ eda_conf_dir }}'
        _postgresql_dest_dir: /etc/eda

    - name: Add postgresql TLS environment variable for certificate authentication
      ansible.builtin.set_fact:
        _common_pg_env: '{{ _common_pg_env | combine(_eda_pg_ssl) }}'
      vars:
        _eda_pg_ssl:
          PGSSLCERT: /etc/eda/postgresql.cert
          PGSSLKEY: /etc/eda/postgresql.key
          PGSSLROOTCERT: '{{ ca_trust_bundle }}'
      when: eda_pg_cert_auth | bool

    - name: Backup the automation eda postgresql database
      community.postgresql.postgresql_db:
        name: '{{ eda_pg_database }}'
        login_host: '{{ eda_pg_host }}'
        login_port: '{{ eda_pg_port }}'
        login_user: '{{ eda_pg_username }}'
        login_password: '{{ eda_pg_password | default(omit) }}'
        login_unix_socket: '{{ eda_pg_socket | default(omit) }}'
        ssl_mode: '{{ eda_pg_sslmode }}'
        target: '{{ ansible_user_dir }}/aap/backups/{{ eda_db_filename }}'
        target_opts: '--clean --create'
        state: dump
      environment: '{{ _common_pg_env }}'
      run_once: true

    - name: Create postgresql CLI aliases
      ansible.builtin.include_role:
        name: postgresql
        tasks_from: cli.yml
      vars:
        _postgresql_socket: '{{ eda_pg_socket | default("") }}'
        _postgresql_cert_auth: '{{ eda_event_persistence_pg_cert_auth }}'
        _postgresql_src_dir: '{{ eda_conf_dir }}'
        _postgresql_dest_dir: /etc/eda
        _postgresql_tls_filename: postgresql_event_persistence
      when: eda_event_persistence_deploy_db | bool

    - name: Add event persistence postgresql TLS environment variable for certificate authentication
      ansible.builtin.set_fact:
        _event_persistence_pg_env: '{{ _common_pg_env | combine(_eda_event_persistence_pg_ssl) }}'
      vars:
        _eda_event_persistence_pg_ssl:
          PGSSLCERT: /etc/eda/postgresql_event_persistence.cert
          PGSSLKEY: /etc/eda/postgresql_event_persistence.key
          PGSSLROOTCERT: '{{ ca_trust_bundle }}'
      when:
        - eda_event_persistence_deploy_db | bool
        - eda_event_persistence_pg_cert_auth | bool

- name: Get the existing eda event persistence db password secret
  containers.podman.podman_secret_info:
    name: eda_event_persistence_db_password
    showsecret: true
  register: _eda_event_persistence_db_password
  no_log: true
  run_once: true
  when:
    - eda_event_persistence_deploy_db | bool
    - not eda_event_persistence_pg_cert_auth | bool

- name: Set the eda event persistence db password fact
  ansible.builtin.set_fact:
    __eda_event_persistence_db_password: '{{ _eda_event_persistence_db_password.secrets[0].SecretData }}'
  no_log: true
  run_once: true
  when:
    - eda_event_persistence_deploy_db | bool
    - not eda_event_persistence_pg_cert_auth | bool
    - _eda_event_persistence_db_password.secrets | default([]) | length > 0

- name: Backup the automation eda event persistence postgresql database
  community.postgresql.postgresql_db:
    name: '{{ eda_event_persistence_pg_database }}'
    login_host: '{{ eda_pg_host }}'
    login_port: '{{ eda_pg_port }}'
    login_user: '{{ eda_event_persistence_pg_username }}'
    login_password: '{{ eda_event_persistence_pg_password | default(__eda_event_persistence_db_password) | default(omit) }}'
    login_unix_socket: '{{ eda_pg_socket | default(omit) }}'
    ssl_mode: '{{ eda_event_persistence_pg_sslmode }}'
    target: '{{ ansible_user_dir }}/aap/backups/{{ eda_event_persistence_db_filename }}'
    target_opts: '--clean --create'
    state: dump
  environment: '{{ _event_persistence_pg_env | default(_common_pg_env) }}'
  run_once: true
  when:
    - eda_event_persistence_deploy_db | bool
    - not eda_postgresql_skip_data | bool or groups.get('database', []) | length == 1

- name: Set automation eda archive paths
  ansible.builtin.set_fact:
    _eda_archive_paths:
      - '{{ ansible_user_dir }}/.local/share/containers/storage/secrets'
      - '{{ ansible_user_dir }}/aap/backups/{{ eda_db_filename }}'
      - '{{ ansible_user_dir }}/aap/eda'
      - '{{ ansible_user_dir }}/aap/tls'

- name: Add event persistence database to archive paths
  ansible.builtin.set_fact:
    _eda_archive_paths: '{{ _eda_archive_paths + [ansible_user_dir + "/aap/backups/" + eda_event_persistence_db_filename] }}'
  when: eda_event_persistence_deploy_db | bool

- name: Archive the automation eda data
  ansible.containerized_installer.archive:
    path: '{{ _eda_archive_paths }}'
    dest: '{{ ansible_user_dir }}/aap/backups/eda.{{ eda_archive_extension }}'
    format: '{{ eda_use_archive_compression | bool | ternary(omit, archive_decompressed_extension) }}'
    mode: '0640'

- name: Download the automation eda tarball
  ansible.builtin.fetch:
    src: '{{ ansible_user_dir }}/aap/backups/eda.{{ eda_archive_extension }}'
    dest: '{{ hostvars["localhost"]["_backup_dir"] }}/eda_{{ inventory_hostname }}.{{ eda_archive_extension }}'
    flat: true
...
