---
- name: Uninstall EDA redis unix socket
  ansible.builtin.include_role:
    name: redis
    tasks_from: uninstall.yml
  when:
    - redis_mode | default('cluster') == 'standalone'
    - groups.get('automationeda', []) | length == 1
    - inventory_hostname not in groups.get('automationcontroller', [])
    - inventory_hostname not in groups.get('automationhub', [])

- name: Remove eda_redis_password podman secret
  containers.podman.podman_secret:
    name: eda_redis_password
    state: absent

- name: Remove TLS redis files
  ansible.builtin.file:
    path: '{{ eda_conf_dir }}/redis.{{ item }}'
    state: absent
  loop:
    - cert
    - csr
    - key
...
