---
- name: Stop and disable the legacy eda scheduler systemd service
  ansible.builtin.systemd:
    name: automation-eda-scheduler.service
    state: stopped
    enabled: false
    scope: user
  failed_when: false

- name: Remove the legacy eda scheduler container
  containers.podman.podman_container:
    name: automation-eda-scheduler
    state: absent

- name: Remove the legacy eda scheduler systemd unit file
  ansible.builtin.file:
    path: '{{ ansible_user_dir }}/.config/systemd/user/automation-eda-scheduler.service'
    state: absent
...
