---
- name: Import event persistence postgresql TLS certificate and key
  when:
    - eda_event_persistence_pg_tls_cert is defined
    - eda_event_persistence_pg_tls_key is defined
  block:
    - name: Copy event persistence postgresql TLS certificate
      ansible.builtin.copy:
        src: '{{ eda_event_persistence_pg_tls_cert }}'
        dest: '{{ eda_conf_dir }}/postgresql_event_persistence.cert'
        mode: '0640'
        remote_src: '{{ eda_tls_remote | default(false) }}'
      notify:
        - Restart eda api
        - Restart eda daphne
        - Restart eda workers
        - Restart eda activation workers

    - name: Copy event persistence postgresql TLS key
      ansible.builtin.copy:
        src: '{{ eda_event_persistence_pg_tls_key }}'
        dest: '{{ eda_conf_dir }}/postgresql_event_persistence.key'
        mode: '0400'
        remote_src: '{{ eda_tls_remote | default(false) }}'
      notify:
        - Restart eda api
        - Restart eda daphne
        - Restart eda workers
        - Restart eda activation workers
...
