---
name: DCO

on:
  pull_request:
    branches: [main, devel]

jobs:
  dco:
    name: Developer Certificate of Origin
    runs-on: ubuntu-24.04
    steps:
      - name: Check DCO
        uses: dcoapp/app@v1
        with:
          require-for-members: false
